### ISSUE TITLE
What to do with 0 (organism absent) ?

### ISSUE THREAD

**Issue by cnrdh** [npolar/marine-db#24]
A surprising high number, over 55000 occurrence records, contains 0 as count (organismQuantity).

Now, absence data may also be valuable, but absence is normally not recorded, ie. there is  no consistent use of 0 for absent.

**Comment by cnrdh** [comment]
Some samples are not (always) counted, eg. MOSJ2017 handnet.

**Comment by AnetteWold** [comment]
For mesozooplankton we use a standard list => species included in this list that was not found are left blanc. I assume blanc is replaced with 0 for some datasets. Not sure what to do
