### ISSUE TITLE
Samplelog corrections for 2014, 2016 & 2017. 

### ISSUE THREAD

**Issue by AnetteWold** [npolar/marine-db#5]
N-ICE2015 er litt detektivarbeid så jeg trenger litt tid for å få det ferdig
2017
     37 "Sal_Temp_pH", slettes
      8 "undefined", slettes
      4 "KpN4_R1_10M; KpN4_R2_10M", den første er riktig de 3 neste skal endres til "KpN2_R1_10M; KpN2_R2_10M", "KpM2_R1_10M; KpM2_R2_10M", "KpS2_R1_10M; KpS2_R2_10M" i denne rekkefølgen
      2 "R6_R1_S; R6_R2_S", jeg finner de ikke i excel fil men kan antagelig slettes
      2 "R6_R1_M; R6_R2_M", jeg finner de ikke i excel fil men kan antagelig slettes
      2 "R6_R1_B; R6_R2_B", jeg finner de ikke i excel fil men kan antagelig slettes
      2 "MOSJ2017/DOX-009", dobbel registrering en av de kan slettes
      2 "MOSJ2017/DOX-008", dobbel registrering en av de kan slettes
      2 "MOSJ2017/DOX-007", dobbel registrering en av de kan slettes
      2 "MOSJ2017/DIC-091", den som er fra R4 skal slettes
      2 "GlacierFront2017/SAL-386", den fra stasjon KpM6 skal endres til SAL-387
      2 "GlacierFront2017/PHT-033", den fra stasjon CpS3 kan slettes
      2 "GlacierFront2017/OXY-161", den fra stasjon CpS4 skal være OXI-163
      2 "GlacierFront2017/OXY-160", den fra stasjon CpS4 skal være OXI-162
      2 "GlacierFront2017/OXY-021", den fra stasjon Kb5 skal være OXY-022
      2 "GlacierFront2017/DIC-079", den fra KpM1 kan slettes
      2 "GlacierFront2017/DIC-078", den fra KpM1 kan slettes
      2 "GlacierFront2017/DIC-077", den fra KpM1 kan slettes
      2 "GlacierFront2017/DIC-076", den fra KpM1 kan slettes
      2 "GlacierFront2017/DIC-033", jeg klarer ikke å se hva som er feil
      2 "GlacierFront2017/DIC-031", jeg klarer ikke å se hva som er feil

2016
  6 "undefined", slettes
     2 "MOSJ2016/ZOT-063", den fra stasjon R5 skal være ZOT-067
     2 "MOSJ2016/ZOT-062", den fra stasjon R5 skal være ZOT-066
     2 "MOSJ2016/ZOT-061", den fra stasjon R5 skal være ZOT-065
     2 "MOSJ2016/ZOT-018", dobbel registrering en av de kan slettes
     2 "MOSJ2016/ZOT-017", dobbel registrering en av de kan slettes
     2 "MOSJ2016/ZOT-016", dobbel registrering en av de kan slettes
     2 "MOSJ2016/ZOT-015", dobbel registrering en av de kan slettes
     2 "MOSJ2016/ZOT-014", dobbel registrering en av de kan slettes
     2 "MOSJ2016/PAB-070", den fra stasjon R2 kan slettes
     2 "MOSJ2016/MAA-045", prøvenummer er forskjøvet for stasjon R5, MAA- 045 skal være MAA-046, MAA-046 skal være MAA-047 & MAA-047 skal være MAA-048
     2 "MOSJ2016/MIT-015", jeg klarer ikke å se hva som er feil
     2 "MOSJ2016/CDO-054", prøvenummer for stasjon V12 har blitt forskjøvet, alle tall skulle vært ett tall lavere (048=047, 049=048, 050=049, 051= 050, 052= 051, 053=052, 054=053)
     2 "GlacierFront2016/NUT-243", prøvenummer for stasjon GF-04 er blitt forskjøvet, alle tall skal være to høyere (042 = 044, 043=045, 044=046)
     2 "GlacierFront2016/NUT-242", samme som NUT-043

2014
2 "MOSJ2014/FCM-068", endres til FCM-052
2 "MOSJ2014/FCM-067", endres til FCM-053
2 "MOSJ2014/FCM-066", endres til FCM-054
2 "MOSJ2014/FCM-065", endres til FCM-055
2 "MOSJ2014/FCM-064", endres til FCM-056
2 "MOSJ2014/FCM-063", endres til FCM-057
2 "MOSJ2014/FCM-062", endres til FCM-058
2 "ICE2014/ZOT-076", den fra R1b kan slettes

**Comment by cnrdh** [comment]
2 "MOSJ2014/FCM-068", endres til FCM-052 => Da blir det 2 FCM-052 :)

**Comment by cnrdh** [comment]
Som sagt over:
```
data/deposit/2014/mosj_ice_2014_samplelog.csv:"MOSJ2014","FCM-052","V6",78.9073,7.7706,1130,"2014-07-24 21:50 UTC","Niskin bottle",500.0,,,"Flow cytometry","Philipp Assmy","Petridish 30 (surface bacteria sample is the lowest sampling number on this station)",
data/deposit/2014/mosj_ice_2014_samplelog.csv:"MOSJ2014","FCM-052","V6",78.9073,7.7706,1130,"2014-07-24 21:50 UTC","Niskin bottle",300.0,,,"Flow cytometry","Philipp Assmy","According to CTD log sheet, samples from 8 depths.",

**Comment by AnetteWold** [comment]
Delete the first one (depth 500m). For the time being we are not storing FCM results in database and the deepest sample is the least important

**Comment by cnrdh** [comment]
All good except 8+6+6 "undefined" in 2017,2016,2014

**Comment by cnrdh** [comment]
For 2017 it's all in MOSJ:
```
$ cat data/master/sample/*2017* | ndjson-filter 'd.sample == "undefined"' | ndjson-reduce | json2csv
expedition,station,latitude,longitude,depth_bottom,time,gear,depth_from,depth_to,sample_type,filtered_volume,responsible,comment,sample,event
MOSJ2017,Kb0,79.047,11.1414,322,2017-07-31T13:30:00.000Z,MIK 1500 μm,300,0,Stable isotopes,,Anette Wold,,undefined,232abe28-efbc-53e3-85df-6c13bb7a7d15
MOSJ2017,V10,78.9335,8.5551,273,2017-08-01T05:02:00.000Z,WP2 200 µm,50,0,Limacina helicina,,Agnetha Fransson; Elizabeth Jones,,undefined,1f7f8db5-f044-5401-8b33-a600df235a7e
MOSJ2017,R1,80.1224,22.1572,201,2017-08-03T11:50:00.000Z,MIK 1500 μm,180,0,Stable isotopes,,Anette Wold,,undefined,32323a22-f517-56f8-a34e-0f0fd2c53e02
MOSJ2017,R1,80.1224,22.1572,201,2017-08-03T11:50:00.000Z,WP3 1000 μm,180,0,Stable isotopes,,Anette Wold,,undefined,32323a22-f517-56f8-a34e-0f0fd2c53e02
MOSJ2017,R3,80.0123,22.3083,218,2017-08-03T17:45:00.000Z,MIK 1500 μm,200,0,Stable isotopes,,Anette Wold,,undefined,18710f50-08e1-5142-af0f-9bfb41fac0e5
MOSJ2017,R5,80.8998,22.1295,130,2017-08-04T09:00:00.000Z,MIK 1500 μm,110,0,Limacina helicina,,Agnetha Fransson; Elizabeth Jones,,undefined,7b62548d-3ebc-570b-84f9-be297aaaabd9
MOSJ2017,R5,80.8998,22.1295,130,2017-08-04T09:00:00.000Z,MIK 1500 μm,110,0,Stable isotopes,,Anette Wold,,undefined,7b62548d-3ebc-570b-84f9-be297aaaabd9
MOSJ2017,R7,81.5059,22.0818,893,2017-08-05T03:04:00.000Z,MIK 1500 μm,400,,Stable isotopes,,Anette Wold,,undefined,22cfa0d9-373b-5e60-a38b-6bc8d00874a8

**Comment by cnrdh** [comment]
Fixed by 
node/sample/rejectSample.mjs:  (s) => ["", "undefined"].includes(String(s.sample)),
